heavyai/heavyai-charting

src/charts/raster-chart.js, src/mixins/coordinate-grid-raster-mixin.js, src/mixins/raster-draw-mixin.js
=> fixes backend scatter filters and resizing behavior

src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer.js, src/utils/utils-vega.js
=> [RASTER] enabling density accumulation on layers

example/example1.html, example/example2.html, example/example3.html, example/example4.html, example/example5.html, example/exampleMultiLayerMap.html, example/exampleMultiLayerScatterplot.html, package.json, scripts/copy-example-libs.sh
- Part of integrating node-connector work: https://github.com/mapd/mapd-connector/pull/22
=> use browser-connector

scss/chart.scss, src/charts/bubble-chart.js, src/charts/row-chart.js, src/mixins/coordinate-grid-mixin.js, src/mixins/coordinate-grid-raster-mixin.js, src/mixins/label-mixin.js, src/mixins/lock-axis-mixin.js
=> axes controls (lock/unlock, min/max) for x and y

src/charts/raster-chart.js
=> [raster chart] fix getResultRowForPixel call

package.json
=> use connector#develop since node-connector merged

package.json
=> update mapd dependencies

src/mixins/coordinate-grid-raster-mixin.js
=> Include height of bottom margin in chart parent to reveal X axis

src/mixins/raster-layer-point-mixin.js
=> dynamically size points in raster point mixin

src/mixins/coordinate-grid-raster-mixin.js, src/mixins/coordinate-grid-raster-mixin.unit.spec.js
=> raster chart: size svg with style props

README.md, example/example2.html, example/example4.js, example/example5.html, example/index.html
=> Raster point size

src/charts/number-chart.js
=> [number chart] fixed tspan on null issue

src/mixins/raster-draw-mixin.js
=> Prevent duplicate draw filters

src/mixins/map-mixin.js
=> add method to customize mapbox attribution location

src/charts/row-chart.js
=> row chart: format nulls for measure value

src/mixins/label-mixin.js, src/mixins/label-mixin.unit.spec.js
=> set correct width for axis label edit container

dist/chart.css, dist/mapdc.js, scss/chart.scss
=> Mousewheel zoom doesn't work when mousing over a point 

src/mixins/coordinate-grid-mixin.js, src/mixins/lock-axis-mixin.js
=> [Line & Histogram] enable lock axis on x

src/charts/bar-chart.js, src/charts/line-chart.js, src/mixins/coordinate-grid-mixin.js
=> remove coordinate-grid-mixin destroy hook

scss/chart.scss, src/charts/pie-chart.js, src/charts/row-chart.js
=> gray out deselected labels for row and pie

src/mixins/raster-draw-mixin.js
=> revert changes to apply draw filters

example/example2.html, example/example3.js, example/example5.html, example/exampleMultiLayerMap.js, example/exampleMultiLayerScatterplot.js
=> set mapbox token in examples

src/mixins/raster-layer-heatmap-mixin.js, src/mixins/raster-layer.js
=> [GEOHEAT] add global filtering to sql generation

src/charts/mapd-table.js, src/core/core-async.js, src/core/core.js, src/index.js, src/mixins/base-mixin.js, src/mixins/coordinate-grid-mixin.js, src/mixins/map-draw-mixin.js, src/mixins/map-mixin.js, src/mixins/raster-draw-mixin.js, src/mixins/ui/coordinate-grid-raster-mixin-ui.js, src/utils/utils.js
=> update redrawAll and renderAll for groups

example/exampleMultiLayerMap.js, package.json, src/chart-addons/stacked-legend.js, src/chart-addons/stacked-legend.unit.spec.js, src/charts/raster-chart.js, src/charts/row-chart.unit.spec.js, src/index.js
=> Stacked Legend For Raster

scss/chart.scss, src/charts/mapd-table.js, src/charts/mapd-table.unit.spec.js
=> add nulls order to table chart

src/charts/raster-chart.js
=> handle error in geoheat data-async call

src/charts/bar-chart.js, src/charts/line-chart.js, src/mixins/coordinate-grid-mixin.js
=> tweak line/bar destroy hook

src/core/core-async.js
=> add option to redraw every chart in registry

package.json, src/chart-addons/stacked-legend.js, src/charts/raster-chart.js
=> polish stacked legend

dist/mapdc.css, dist/mapdc.js, src/core/core-async.js, src/core/core-async.unit.spec.js
=> throw error if redrawAllAsync is called before renderAllAsync

scss/chart.scss
Handling Odyssey and Decimal links.
=> Handling 2 more dark maps.

scss/chart.scss, src/chart-addons/stacked-legend.js
=> handle default open states for stacked legend

src/mixins/map-mixin.js
Exposes the zoomToLocation method and validate bounds, for task [#3449](https://github.com/mapd/mapd-immerse/issues/3449) and [PR 3493](https://github.com/mapd/mapd-immerse/pull/3493)
=> zoomToLocation

.eslintrc.json, example/example2.html, example/example3.js, example/example4.js, example/example5.html, example/exampleMultiLayerMap.js, example/exampleMultiLayerScatterplot.js, package.json, scss/chart.scss, src/chart-addons/stacked-legend.js, src/chart-addons/stacked-legend.unit.spec.js, src/charts/count-widget.js, src/charts/number-chart.js, src/charts/raster-chart.js, src/core/core-async.js, src/core/core.js, src/index.js, src/mixins/coordinate-grid-raster-mixin.js, src/mixins/label-mixin.js, src/mixins/map-mixin.js, src/mixins/raster-draw-mixin.js, src/mixins/raster-layer-heatmap-mixin.js, src/mixins/raster-layer-heatmap.unit.spec.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-point-mixin.unit.spec.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js, src/mixins/raster-layer.js, src/utils/utils-vega.js, src/utils/utils.js
=> Raster Layer API as Vega-Lite Spec

src/charts/mapd-table.js, src/core/core-async.js
=> update table chart filterCol to handle timestamp and date cases

dist/mapdc.css, dist/mapdc.js, scss/chart.scss, src/charts/mapd-table.js
=> Enable table text select without filter

src/charts/heatmap.js
=> Heatmap: fix axis text calc when domain contains null values

src/charts/heatmap.js
=> heatmap: improve handling of null vals in axes labels

src/mixins/binning-mixin.js, src/utils/binning-helpers.js
- [s] author crafted PR's title into release-worthy commit message.
=> Simplify handling of auto binning

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js
=> use x,y,xc,yc as render attributes

example/example3.js, example/example4.js, example/example5.html, example/exampleGeoHeat.js, example/exampleMultiLayerMap.js, example/exampleMultiLayerScatterplot.js, package-lock.json, package.json, scss/chart.scss, src/charts/raster-chart.js, src/mixins/map-mixin.js, src/mixins/raster-draw-mixin.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js, src/mixins/raster-layer.js, src/utils/utils.js
=> Vega spec to support poly raster layer in immerse

dist/mapdc.js, package.json, src/charts/geo-choropleth-chart.js
Improvement on https://github.com/mapd/mapd-charting/pull/139 to use TurfJS's bbox module
=> Use TurfJS bbox for geo-choropleth findGeomMinMax

dist/mapdc.js, src/mixins/raster-layer.js
See https://github.com/mapd/mapd-immerse/issues/4390
=> Fix formatting in pointmap and scatterplot

dist/mapdc.js, src/mixins/binning-mixin.js
=> fixed line chart dimension binning and cross filtering bug

dist/mapdc.js, package-lock.json, package.json, src/charts/number-chart.js, src/utils/utils.js
=> simpler and reusable logic to get the right font-size on number chart

package.json
was pointing to crossfilter master, now points to a specific commit
=> crossfilter bf77150

example/example-rendervega.html
=> minimal example of using renderVega

.prettierignore, dist/mapdc.js, package.json, src/charts/raster-chart.js, src/charts/row-chart.js, src/mixins/cap-mixin.js, src/mixins/map-mixin.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js, src/polyfills/inner-svg.js
=> Poly geo types updates

scss/chart.scss
=> Changing editing font color to black

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-point-mixin.unit.spec.js
Relates to Immerse https://github.com/mapd/mapd-immerse/issues/4334
=> point map Other color bug fixed

src/mixins/raster-layer-point-mixin.js
=> point map lastFilteredSize bug fix

dist/mapdc.css
=> compiling scss

dist/mapdc.js, src/charts/mapd-table.js, src/charts/pie-chart.js, src/charts/row-chart.js, src/mixins/base-mixin.js, src/mixins/multiple-key-label-mixin.js
* using key for row, pie, table format
* works with extract, unique, #record
Works with Immerse PR https://github.com/mapd/mapd-immerse/pull/4465
=> custom measure, extract

dist/mapdc.js
=> including mapdc for release

src/charts/row-chart.js
=> negative single bar

package.json, yarn.lock
=> Infra: update crossfilter and connector dev deps

dist/mapdc.js, src/chart-addons/stacked-legend.js
=> Fixes legend locking for chorpleth/pointmap with 'auto' color domains

dist/mapdc.js, example/exampleMultiLayerMap.js, example/exampleMultiLayerScatterplot.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js
=> Choropleth API improvements

src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js
Add framework for ordinal scales, clean up existing filtering for solid and quantize scales.
Reference https://github.com/mapd/mapd-immerse/pull/4693
=> Refactor poly layer transform code

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
=> Fix issue creating filter for choropleth with geojoin

dist/mapdc.css, dist/mapdc.js, src/charts/mapd-table.js, src/mixins/base-mixin.js
The query was wrong when binning was off because of a bad format of some data attached to the DOM in a mapdc listener
Exposed in Immerse here: https://github.com/mapd/mapd-immerse/pull/4710
=> filter format when binning is off

src/mixins/legend-mixin.js
Fixes https://github.com/mapd/mapd-immerse/issues/4061
Before: 
After:
=> use chart formatter on legend

package.json
Update crossfilter dev dep to include knuth multiplicative hash fix
=> update dev dep crossfilter

dist/mapdc.js, src/chart-addons/stacked-legend.js
https://github.com/mapd/mapd-immerse/pull/4891
=> locking heat map legend defaulting min/max right after adjusting 

src/charts/geo-choropleth-chart.js
=> Error thrown when clicking on choropleth chart in mahakali

dist/mapdc.js, package.json, yarn.lock
=> legendable commit hook to support boolean domain in nominal legend

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
=> Choropleth filter with color measure throws error

dist/mapdc.js, src/mixins/raster-layer-line-mixin.js
=> [FE-5458] changed linejoin option to bevel

dist/mapdc.js, src/mixins/raster-layer-line-mixin.js
=> [FE-7459] bug fix for geo cols with any name

dist/mapdc.js, src/charts/pie-chart.js
https://jira.omnisci.com/browse/FE-7325
=> fix null dim handling and other label issues

dist/mapdc.js, src/chart-addons/stacked-legend.js
https://jira.omnisci.com/browse/FE-7401
=> [FE-7401] handle all null color measure column legend

dist/mapdc.js, package.json, src/mixins/map-mixin.js, yarn.lock
For simple bounding box filtering, we decided to use ST_Min and ST_Max instead of ST_Intersects for Linemap chart.
https://github.com/omnisci/mapd-crossfilter/pull/67
=> [FE-7438] change ST_Intersects to ST_Min and ST_Max filter

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-7485] change Linemap hit testing to match with Pointmap hit testing logic

dist/mapdc.js, src/mixins/map-mixin.js
=> [FE-7493] Remove extra canvas before adding layer on the map

src/charts/heatmap.unit.spec.js, src/utils/formatting-helpers.js, src/utils/formatting-helpers.unit.spec.js
Default number format to be float, k, M, B
=> default number format

dist/mapdc.js, example/example3.js, example/exampleLinemap.html
=> [FE-7492] fix poly map example and update linemap crossfilter method

dist/mapdc.js, package.json, yarn.lock
=> updating crossfilter

dist/mapdc.js, src/charts/heatmap.unit.spec.js, src/utils/formatting-helpers.js, src/utils/formatting-helpers.unit.spec.js
https://jira.omnisci.com/browse/FE-7694
=> revert default number fix

example/exampleMultiLayerMap.js, example/exampleMultiLayerScatterplot.js
=> [FE-7715] fix Multilayer and Multilayer Scatterplot examples

dist/mapdc.js, package.json, src/mixins/base-mixin.js, yarn.lock
=> [FE-7720] Heat chart - swap selector registers extra chart

dist/mapdc.js, package.json, src/mixins/raster-draw-mixin.js, yarn.lock
=> [FE-5247] Linemap selection filter

dist/mapdc.js, package.json, src/mixins/raster-layer-point-mixin.unit.spec.js, yarn.lock
=> [FE-7719] Correct Knuth's multiplicative hash magic number with modulo arithmetic

src/utils/utils.js
fix all UTC and hunt for more local time zones
=> hunt for non-utc date formatters

dist/mapdc.js, src/charts/raster-chart.js
=> Remove async and fix tests

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js
Fix handling of string-parsed custom color measure on choropleth, and move color projection to after geo for proper backend parsing
=> Fix handling of string-parsed custom color measure on choropleth

dist/mapdc.css, dist/mapdc.js, src/mixins/map-mixin.js
=> [FE-8084] Disable map rotation

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
=> [FE-8263] Remove poly selection filter when chart deleted

dist/mapdc.js, package.json, src/mixins/raster-layer-point-mixin.unit.spec.js, yarn.lock
=> [FE-8323] use thirty one bits in MOD sampling calculation

src/utils/utils-vega.js
Alternative fix for FE-7408. Replaces quantize scale by linear when domain min/max are the same; Also detects the "Other" color item so it uses the proper default "Other" color.
Also fixes an unfiled bug where color for Other categories are not blue:
Before:
After:
=> Tooltip offset problem

src/utils/binning-helpers.js
=> [FE-8345] adds default time bin interval for single group binning

package.json
=> Pegged mapd-draw to it's latest release tag

dist/mapdc.js, package.json, src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-poly-mixin.js, yarn.lock
This modification supports applying sampling for geo joined choropleth chart to improve the distributed poly rendering performance.
Related with: 
https://github.com/omnisci/metis/pull/57 and 
https://github.com/omnisci/mapd-immerse/pull/5494
=> Add sampling on geo joined poly

dist/mapdc.js, package.json, src/mixins/raster-layer-poly-mixin.js, yarn.lock
https://github.com/omnisci/metis/pull/60
https://github.com/omnisci/mapd-immerse/pull/5513
=> [FE-8635] use colors for geo joined sampled poly filter

dist/mapdc.js, package.json, yarn.lock
Bumps the metis and mapd-crossfilter versions to bring in the binning changes.
Needs to be updated to point to new version hashes as they get merged, etc etc etc
=> [FE-8602] - bumps metis and crossfilter hashes

dist/mapdc.js, src/charts/raster-chart.js
=> [FE-8669] multi poly chart Master layer sends endless requests

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
https://github.com/omnisci/mapd-immerse/pull/5530
=> [FE-8685] disable poly filter on master

dist/mapdc.js, src/charts/raster-chart.js, src/mixins/raster-layer-poly-mixin.js
=> [FE-7786][FE-8700]  incorrect filter on poly

package.json, yarn.lock
Just bumped the mapd-data-layer version as per FE-8667.
=> [FE-8667] - bumps mapd-data-layer version

package-lock.json, package.json
Bump mapbox-gl fork to include the fast-stable-stringify bump to 0.2.0 (to fix licensing issues)
=> [FE-8777] Bump mapbox-gl to include fast-stable-stringify bump

dist/mapdc.js, src/charts/raster-chart.js, src/mixins/map-mixin.js
Relates with: https://github.com/omnisci/mapd-immerse/pull/5607
=> [FE-8867] Add check for WebGL modal related error 

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
Relates with: https://github.com/omnisci/mapd-immerse/pull/5619
=> [FE-7582] Fix Choropleth Other color to match with color palette Other color

package-lock.json, package.json
https://github.com/omnisci/mapbox-gl-js/tree/mapbox-gl-style-spec-fork
https://github.com/omnisci/mapbox-gl-style-spec/tree/fast-stable-stringify-bump
=> [FE-8937] Bump mapbox-gl to commit 3523136 to include fast-stable-stringify bump

src/mixins/map-mixin.js, src/mixins/raster-draw-mixin.js
=> [FE-9522] temporarily disable the new mapbox mouse events

dist/mapdc.css, dist/mapdc.js, package-lock.json, scss/chart.scss, src/mixins/map-mixin.js
=> [FE-8050] Add scale bar to the map charts

dist/mapdc.css, dist/mapdc.js, scss/chart.scss, src/mixins/map-mixin.js
=> [FE-9658] moved map scale to bottom right

dist/mapdc.js, src/mixins/map-mixin.js
=> [FE-9423] Streets and Outdoors theme under omnisci layer, but label on top

dist/mapdc.js, src/utils/mapbox-ported-functions.js
Relates with https://github.com/omnisci/mapd-immerse/pull/5950
=> [FE-9776] fix BE Scatter box zoom

dist/mapdc.js, src/mixins/legend-mixin.js
=> [FE-5314] fix legend domain range calculation

dist/mapdc.js, src/charts/raster-chart.js
Relates with https://github.com/omnisci/mapd-immerse/pull/5967
=> [FE-9800] Set premultipliedAlpha to true for BE Scatter

dist/mapdc.js, package-lock.json, src/mixins/raster-layer-poly-mixin.js
Relates with https://github.com/omnisci/mapd-immerse/pull/5981
=> {FE-9807] fix clear filter error on geo joined poly

dist/mapdc.js, src/mixins/raster-draw-mixin.js
Relates with https://github.com/omnisci/mapd-immerse/pull/5970
=> [FE-9799] clear poly filter upon shape filter deletion

dist/mapdc.js, src/mixins/map-mixin.js
=> [FE-9833] fix blank map without rendered image

dist/mapdc.js, src/charts/heatmap.js, src/mixins/bubble-mixin.js
=> [FE-10396]  fix bubble chart filter on extract

package-lock.json, package.json
Just a package bump to version 1.1.0 to prepare for publishing.
=> Version 1.1.0

dist/mapdc.js, src/charts/heatmap.js, src/utils/utils.js
=> [FE-9259] Heat map column ordering with dates

dist/mapdc.js, package-lock.json, package.json, src/charts/heatmap.js, src/mixins/async-mixin.js, src/mixins/stack-mixin.js, src/utils/utils.js
=> Fixes issues w/ upper and lower bounds in binning for histogram

dist/mapdc.js, src/charts/heatmap.js, src/mixins/base-mixin.js, src/mixins/map-mixin.js
=> [F-9039] Linked zoom event listener

dist/mapdc.js, src/charts/heatmap.js, src/charts/raster-chart.js
Relates with: https://github.com/omnisci/mapd-immerse/pull/6592
=> [FE-11176] stuck polygon popup

dist/mapdc.js, src/mixins/raster-layer-heatmap-mixin.js, src/mixins/raster-layer-heatmap.unit.spec.js, src/utils/utils.js
Relates with: https://github.com/omnisci/mapd-immerse/pull/6664
=> [FE-11202] Support packed-pixel-coords hex and rect maps

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
https://github.com/omnisci/mapd-immerse/pull/6708
=> [FE-11488] update layer filters before chart filters

dist/mapdc.js, src/mixins/raster-layer-heatmap-mixin.js, src/mixins/raster-layer-heatmap.unit.spec.js, src/utils/utils.js
Reverts omnisci/mapd-charting#428
Relates with https://github.com/omnisci/mapd-immerse/pull/6709
Closing: https://omnisci.atlassian.net/browse/FE-11493
Reverting until we have full support from BE.
=> Revert "[FE-11202] Support packed-pixel-coords hex and rect maps"

src/charts/raster-chart.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer.js
Immerse PR is forthcoming. This is the backend mods for it.
Closes [FE-11527](https://omnisci.atlassian.net/browse/FE-11527)
Closes [FE-11517](https://omnisci.atlassian.net/browse/FE-11517)
=> [FE-11527][FE-11517] - added support for tickets

dist/mapdc.css, dist/mapdc.js, scss/chart.scss, src/mixins/map-mixin.js
https://github.com/omnisci/mapd-immerse/pull/6910
=> [FE-11800] Show mouse position - lat and long

dist/mapdc.css, dist/mapdc.js, scss/chart.scss, src/mixins/map-mixin.js
https://github.com/omnisci/mapd-immerse/pull/6914
=> [FE-11941] Styling change for lat, lon on map

dist/mapdc.js, src/mixins/map-mixin.js, src/mixins/ui/coordinate-grid-raster-mixin-ui.js
=> [FE-12062][FE-12063] - logic fixes for shift to zoom

dist/mapdc.js, src/charts/geo-choropleth-chart.js
added shift-to-zoom to fe choropleth whatever.
=> [FE-12116] fe shift to zoom fix

dist/mapdc.js, src/mixins/map-mixin.js, src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-poly-mixin.js
=> [FE-12111] generalize raster encoding

dist/mapdc.js, src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-poly-mixin.js
Relates with: https://github.com/omnisci/mapd-immerse/pull/7045
=> [FE-12158] Use ST_POINT in pointmap data export sql query

dist/mapdc.js, src/charts/heatmap.js, src/mixins/coordinate-grid-mixin.js, src/mixins/lock-axis-mixin.js, src/utils/formatting-helpers.js
Implements lock axis controls for heatmap
companion `immerse` PR: https://github.com/omnisci/mapd-immerse/pull/6992
=> [FE-11697] - min max heatmap controls

dist/mapdc.js, src/charts/heatmap.js, src/mixins/lock-axis-mixin.js
Immerse companion PR: https://github.com/omnisci/mapd-immerse/pull/7083
=> Fixes https://omnisci.atlassian.net/browse/FE-12249

dist/mapdc.js, src/mixins/raster-layer.js
https://github.com/omnisci/mapd-immerse/pull/7092
=> [FE-12258] Convert map date type popup to UTC 

dist/mapdc.js, src/mixins/lock-axis-mixin.js
=> [FE-12346] enforce min max limits

dist/mapdc.js, src/mixins/lock-axis-mixin.js
=> [FE-12283] fix heat y binning controls

dist/mapdc.js, src/charts/heatmap.js, src/mixins/lock-axis-mixin.js, src/utils/binning-helpers.js
=> [FE-12278] fix y sorting

dist/mapdc.js, src/charts/heatmap.js, src/mixins/coordinate-grid-mixin.js
=> [FE-12408] fix bottom of bin changing unlock

dist/mapdc.js, src/core/core-async.js, src/utils/binning-helpers.js
=> [FE-12408] - fix for chart redraw on filtering

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-12418] Convert date to UTC not UTC string to support date formatter

dist/mapdc.js, src/charts/heatmap.js
=> [FE-12465] - Fixes extract for heatmaps

dist/mapdc.js, src/charts/raster-chart.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer.js
=> [FE-12664] Support custom column  in popup

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-12798] Fix scatter popup with custom lat/lon measure

dist/mapdc.js, src/mixins/map-mixin.js
=> [FE-12589] Fix lost render image after basemap changes

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-9992] Inlude null values in popup

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-12862] Include column expression in hit-testing

package.json
Bump legendables which includes minor style fix for [FE-12895](https://omnisci.atlassian.net/browse/FE-12895)
=> [FE-12895] Bump legendables

package.json
Bump version for publishing latest changes
=> Bump package.json to 2.1.0

dist/mapdc.js, package-lock.json, src/chart-addons/stacked-legend.js, src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js, src/utils/utils-vega.js
https://github.com/omnisci/mapd-immerse/pull/7398
=> [FE-12932] Toggle Other category 

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js, src/utils/utils-vega.js
=> [FE-13003] Added angle orientation support in pointmap

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js, src/utils/utils-vega.js
=> [FE-13034] Support angle/orientation in multilayer

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js
=> [FE-13057] Fix orientation popup with dimension

dist/mapdc.js, src/mixins/filter-mixin.js
I'm not sure how this code ever worked - it was certainly relying on some javascript dark magic wrt `==` as one or both of the filter and test values are typically arrays.
=> [FE-13035] fix filters on bool values

dist/mapdc.js, src/mixins/raster-layer-poly-mixin.js
=> [FE-13106] Fix All Other opacity on poly

dist/mapdc.js, src/charts/raster-chart.js
=> [FE-13176] Added temp workaround for null point

dist/mapdc.js, src/charts/mapd-table.js
The formats are keyed off label, not expression.
=> [FE-13263] :bug: fix measure format on custom measures

dist/mapdc.js, src/charts/bar-chart.js, src/constants/dates-and-times.js, src/utils/binning-helpers.js, src/utils/binning-helpers.unit.spec.js
=> [FE-13265] Format time constants

dist/mapdc.js, src/mixins/filter-mixin.js
=> [FE-13284] Fix filter comparison

dist/mapdc.js, src/mixins/binning-mixin.js, src/mixins/coordinate-grid-mixin.js
If you create a brush and then drag the brush to the edge of the chart, this PR will prevent you from dragging the brush off the chart.
=> [FE-8313] disallow dragging brush off chart

dist/mapdc.js, src/mixins/raster-layer.js
=> [FE-13337][FE-13340][FE-13179] Fix hit testing with custom columns

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer.js
=> [FE-13289] Fix custom angle popup issue

dist/mapdc.js, src/utils/utils-vega.js
=> [FE-13372] Use constant domain for angle

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js
https://github.com/omnisci/mapd-immerse/pull/7589
=> [FE-13369] Enlarge wedge and arrow shape

dist/mapdc.css, dist/mapdc.js, scss/chart.scss, src/charts/raster-chart.js, src/mixins/raster-layer.js
=> [FE-12518] Popup url link and open in new tab

dist/mapdc.js, src/chart-addons/stacked-legend.js, src/charts/raster-chart.js, src/mixins/raster-layer-point-mixin.js, src/utils/utils-vega.js
=> [FE-13136] Prioritized color (z-index) hack in Pointmap categorical color

dist/mapdc.js, src/charts/raster-chart.js, src/mixins/raster-layer-point-mixin.js
##: Relates with: https://github.com/omnisci/mapd-immerse/pull/7612
=> [FE-13443] Prevent adding the same layer multiple times

dist/mapdc.js, src/charts/raster-chart.js, src/mixins/raster-layer-point-mixin.js
=> [FE-13448] Fix retrieving crossfilter for prioritized layer

dist/mapdc.js, src/charts/mapd-table.js
=> [FE-13437] adds sort icon svg

dist/mapdc.js, src/mixins/map-mixin.js
Adds support for an optional zoom parameter for location queries.
Corresponding Immerse PR: ...
=> [FE-13283] Add support for zoom level query input

dist/mapdc.js, src/charts/row-chart.js, src/mixins/cap-mixin.js
Should fix "others" support in the row chart.
=> [FE-12008] fix "others" in row chart

dist/mapdc.js, src/mixins/async-mixin.js, src/mixins/coordinate-grid-raster-mixin.js
Reverts omnisci/mapd-charting#537
There's a failing test on immerse, so backing this out of master until that's resolved.
=> Revert "[FE-13791][IHS] - fix scatter chart related slowdowns"

dist/mapdc.js, src/mixins/raster-layer-point-mixin.js
=> [FE-14213] - Fixes pointmap transforms generating duplicate SQL for export queries

package-lock.json, package.json
=> Major version bump

dist/charting.js, package-lock.json, src/charts/heavyai-table.js
Add zebra striping functionality into charting.  Passes in the current zebra striping state from immerse and conditionally applies classes if `true`.
Closes [FE-15103](https://heavyai.atlassian.net/browse/FE-15103)
=> [FE-15103] Table chart zebra striping functionality

dist/charting.js, src/mixins/map-mixin.js
Let's you specify the maxBounds on your map, and you _cannot_ zoom out beyond them.
This is useful if there is a country which does not exist and that you don't want people to see.
=> [FE-15434] max bounds to map

dist/charting.js, src/mixins/map-mixin.js
=> [FE-15469] [Choropleth] Able to apply a filter in an empty place where the image is not rendered

example/exampleContour.html, src/charts/raster-chart.js, src/mixins/raster-layer-poly-mixin.js, src/utils/utils-contour.js
=> Contour polygon layer

src/mixins/raster-layer-poly-mixin.js, src/mixins/raster-layer-poly-mixin.unit.spec.js
=> [FE-16050] Fix polygon scale creation 

src/utils/utils-contour.js
Receives a new prop from the immerse pseudo-query that tells charting whether or not the dimensions are numerical or geo point types; adjusts sql query accordingly.
=> [FE-16082] Check for geo points, adjust sql if they are sent

src/utils/utils-contour.js
=> [FE-16020] Hook up bin_dim_meters param for contours TF

src/mixins/raster-draw-mixin.js
=> Adds code to load cross-section line data from a serialized json

src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-poly-mixin.js, src/utils/utils-contour.js
Background (slackground?) on this optimization: https://heavy-ai.slack.com/archives/C045DL4QM0D/p1670285400029139
=> [FE-16161] Optimize contour sql

src/utils/utils-contour.js
Uses selected agg_type in the `select` portion of the contour layer queries
=> [FE-16118] Contour measure aggregators

src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-poly-mixin.js
=> [FE-16233] Setup x and y dims for line and poly layer

src/utils/utils-contour.js
=> [FE-16607] Contour + Join Compatibility

src/mixins/raster-layer-cross-section-terrain-mixin.js
Add needed prop descriptor to render opacity in vega json for terrain layer
=> [FE-16811] Add opacity prop descriptor for terrain mixin

src/chart-addons/stacked-legend.js, src/mixins/coordinate-grid-raster-mixin.js
Fixes: 
- https://heavyai.atlassian.net/browse/FE-16804 - error caused by closing legend
- https://heavyai.atlassian.net/browse/FE-16818 - legend error when switching between layers and master
- https://heavyai.atlassian.net/browse/FE-16808 - annoying bug where sometimes the y2 axis wouldn't render on the end of the x axis, but rather ~ 0.9
=> [FE-16804] [FE-16808] [FE-16818] Legend and y2-axis rendering bugs

src/mixins/render-vega-lite/Definitions/Transform/Transforms/CrossSection2dDefinitionObject.js, src/mixins/render-vega-lite/Definitions/Transform/Transforms/CrossSectionTerrainDefinitionObject.js
Changes vega json rendered by Cross Section layer to match new renderer API.
=> [FE-16840] Change cross section config to support new vega json format

src/charts/heavyai-table.js, src/mixins/base-mixin.js, src/mixins/raster-layer-cross-section-terrain-mixin.js, src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-mesh2d-mixin.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-point-mixin.unit.spec.js, src/mixins/raster-layer-windbarb-mixin.js, src/mixins/raster-layer.js
=> [FE-16879] Filters + Crossfilter + Join Data Sources

src/utils/utils-contour.js
=> [FE-17342] Cast as big int to avoid non integer in modulo operation errors

src/mixins/raster-layer-line-mixin.js
Use the table property on the size measure to accommodate joined sources
=> [FE-17444][Linemap][Joins] Correct table isn't used for size measure

src/mixins/raster-layer-point-mixin.js
Add `queryOverride` property so we can send queries directly from immerse (needed to generate pointmap visualizations in heavyiq)
=> [FE-17393] Add queryoverride propery

src/mixins/raster-layer-poly-mixin.js
=> [FE-18034] Exclude rowid from filters for poly chart vega query only

src/charts/bubble-chart.js, src/charts/pie-chart.js, src/mixins/color-mixin.js
See Immerse PR: https://github.com/heavyai/immerse/pull/9442
=> [FE-18119] Update D3 colors from mapping domain/range

src/charts/bubble-chart.js, src/charts/pie-chart.js, src/mixins/base-mixin.js, src/mixins/color-mixin.js
See Immerse PR: https://github.com/heavyai/immerse/pull/9444
=> [FE-18120] Disable color by dim with 1 dimension

src/charts/bubble-chart.js
=> [YOLO] Set customdomain/range before updating

src/charts/pie-chart.js
=> Same for pie chart

dist/charting.css, package-lock.json, package.json, scss/chart.scss, src/mixins/map-mixin.js
=> [FE-15599] Add ruler control to mapbox map

dist/charting.css, scss/chart.scss
=> [FE-15599] Ruler style adjustments

src/chart-addons/stacked-legend.js, src/mixins/raster-layer-line-mixin.js, src/mixins/raster-layer-point-mixin.js, src/mixins/raster-layer-poly-mixin.js, src/utils/color-helpers.js, webpack.config.js
See Immerse PR for details: https://github.com/heavyai/immerse/pull/9460
=> [FE-18151] Full color hashing

src/mixins/raster-layer-point-mixin.js
=> [FE-18022] Fixes for scatter export

src/charts/raster-chart.js, src/utils/utils-vega.js
See Immerse PR for details: https://github.com/heavyai/immerse/pull/9470
=> [FE-18152] Add scatter log scale support

src/mixins/map-mixin.js
=> [FE-18020] Configurable map units
