dist/mapdc.js
src/charts/bar-chart.js
src/charts/line-chart.js
src/mixins/base-mixin.js

Fixes: non-cumulative values, ordering, for all layers, no pop-up on range chart

histogram tooltip fixes

---

dist/mapdc.js
example/exampleMultiLayerMap.js
src/mixins/map-mixin.js

Expose mapbox access token to map-mixin as .mapbboxToken. Also recompiled mapdc.js.
Works mapd-immerse PR mapd/mapd-immerse/pull/3086
* open exampleMultiLayerMap.html in browser
* edit exampleMultiLayerMap.js mapboxToken
* verify in Chrome dev tools Network that the right token is used

Expose mapbox access token to map-mixin as .mapbboxToken

---

src/core/core-async.js
src/mixins/multi-series-mixin.js

Two changes:
1. We now reset `groupAll` when resetting state. 
1. we don't re-apply the case statement to the multi-series dimension if its already transformed into a case statement.

reset groupAll when reseting state + multi-series fixes

---

package.json

upgrade legendables for ie numeric input fix

---

dist/mapdc.js
src/chart-addons/stacked-legend.js

Fixes unclickable draw tools, restore vertical draw panel, reposition legend bottom-left. All these bugs has as common cause: the legend positioned on top-left.

Reposition legend bottom-left to also fix draw panel #3894

---

src/chart-addons/stacked-legend.js

Restore top-right positioning for ordinal legend

keep ordinal legend top-right

---

dist/mapdc.js
src/mixins/coordinate-grid-mixin.js

When clearing the format dropdown in Immerse, this makes the axis reverts to mapd-charting format

clear axis format when dateFormatter or valueFormatter are null

---

dist/mapdc.js
src/charts/number-chart.js
src/charts/row-chart.js
src/mixins/coordinate-grid-mixin.js
src/mixins/coordinate-grid-raster-mixin.js

Relates to Immerse PR https://github.com/mapd/mapd-immerse/pull/4423
* Caches changes to the axes tickFormat (from direct access to the axis from outside) to get back to it when clearing custom format
* simple fix to number chart and row chart

revert to default format on axes; fix to table and row chart

---

scss/chart.scss

Fixes legend colors for dark maps:

Fixing gradient legend style for dark maps

---

src/charts/mapd-table.js
src/mixins/base-mixin.js
src/mixins/filter-mixin.js

Description: previously the measure filter on column is only applied in the table chart not the global filter in dashboard level. Contrastingly, only dimension filter in table chart was modifying the global filter. However, the measure filter on column values were crossfiltering across other charts, so it was a confusing UX for the users if they are not sure dimension filter (grouped) is filtering differently than the measure filter. Thus, this change will apply the measure filter on column to the global filter as same as dimension filter. 
Check the build on https://github.com/mapd/mapd-immerse/pull/4484
Please check the description on the related immerse  PR to reproduce the reported issue.

column filter on measure will update global filter

---

dist/mapdc.js
src/chart-addons/stacked-legend.js
src/mixins/raster-layer-point-mixin.js
src/mixins/raster-layer-point-mixin.unit.spec.js
src/mixins/raster-layer-poly-mixin.js
src/mixins/raster-layer-poly-mixin.unit.spec.js
src/utils/utils-vega.js

for point/symbol/poly marks using vega transforms. Quantitative
scales will use the range +/-2 standard deviations from the mean.
Ordinal scales will use distinct

Adding support to auto-popuplate the domain of color/size scales

---

src/charts/number-chart.js
src/utils/utils.js

The way we calculate the font-size is that we add it to the DOM to compute its size, then we can calculate its font size value. But the temporary span that it was in was inside the number chart panel, which gets `display:none` when another chart is opened in the chart editor, which disables `getBoundingClientRect` calculation. So the fix was to add the temporary div outside of the potentially hidden parent.
Can be tested here: https://github.com/mapd/mapd-immerse/pull/4529

Better font calculation

---

src/charts/mapd-table.js
src/mixins/multiple-key-label-mixin.js

Related with https://github.com/mapd/mapd-crossfilter/pull/56

fixed date format not formatting other time units besides TIMESTAMP

---

.gitignore
src/charts/row-chart.js
src/utils/formatting-helpers.js
src/utils/formatting-helpers.unit.spec.js

Fixes https://github.com/mapd/mapd-immerse/issues/4765 by caching the format that is passed using mapdc API. Same fix as #198 but wrapped in a module (which could be used to polish #198)

format cache module

---

dist/mapdc.js
package.json
src/charts/geo-choropleth-chart.js
src/mixins/map-mixin.js

Clamp bounds to values close to +/-180 longitude, +/-85 lattitude. Clip geojson and zoom requests to map bounds.

Uniformly handle mapbox bounds

---

README.md
package.json
yarn.lock

MapD is now OmniSci, and our GitHub org has changed names from `mapd` to `omnisci`. This PR changes the URLs for some dependencies in `package.json` that pointed at the old org, to point to the new one.

Change dependency URLs from old `mapd` org to new `omnisci` org [FE-5366]

---

dist/mapdc.js
src/charts/geo-choropleth-chart.js

There's a bug in Immerse where it would crash if you clicked on the "Dashboards" link in the navbar while viewing a dashboard with a choropleth chart. The source of this appears to be mapd-charting sending a "remove legend" event in its `destroyChart()` function. Immerse will remove the chart from its state, then see the event and try to remove the legend from the already removed chart, leading to an error.
This PR makes it so the choropleth chart will not try to remove its legend when destroyed. This behavior is in line with the way other charts behave.

Fix crash when switching away from a dashboard with a choropleth chart [FE-5321]

---

dist/mapdc.js
src/mixins/map-mixin.js
src/mixins/raster-layer-line-mixin.js

Geo measure dropdown could have more than one geo column selections when the chart is geo joined with two datasets that both have geo column. For example, fact table has `omnisci_geo` and the geo table has `mapd_geo` column. The issue addressed here is support selecting either geo measure column from dropdown.

Make geo column selection work for both tables

---

dist/mapdc.js
src/mixins/raster-layer-line-mixin.js

Support groupby on dimension only without geo join.

[FE-7314], [FE-7313], LINEMAP: run groupby on dimension 

---

dist/mapdc.js
src/mixins/raster-layer-line-mixin.js
src/utils/utils-vega.js

Support ability to use custom sql on Linemap size and color measure selections.

[FE-7399] support custom sql measure

---

dist/mapdc.js
package.json
src/utils/formatting-helpers.js
yarn.lock

This PR adds a non-number check to `formatNumber()` in `formatting-helpers.js`. In the case of a non-number, it returns the string `"NULL"`.
Further, it appears that the source files were not compiled to reflect the latest `master` changes. This PR updates the compiled files to reflect both `master` and these changes.

[FE-7636] Add a null check to `formatNumber()`, recompile source

---

package.json
yarn.lock

Follow-up from https://github.com/omnisci/mapd-charting/pull/283 and https://github.com/omnisci/mapd-charting/pull/282, merging in https://github.com/omnisci/legendables/pull/7

[FE-7636] Update legendables to master commit 5f569b6

---

dist/mapdc.js
src/mixins/map-mixin.js

[FE-7750] Fix inconsistent display of mapbox logo / watermark 

---

scss/chart.scss

prevent blocking a zoom when cursor is hover popup that swallows the events

[FE-7547] Unable to zoom in and out while hovering over active popup

---

src/core/core-async.js

This `allCharts` was introduced here https://github.com/omnisci/mapd-charting/pull/113/files 
It seems to fix the bug. The reasoning is that renderAll should always be called on all charts.
My understanding is that `chartRegistry.list(group)` is the old behaviour, it would render all charts that are in the same group, but it’s not used in Immerse (notice the null in the main use in dc-action-creators.js):
```.renderAllAsync(null, true)```
combo is using the `group` argument in line2-dc-adapter
```dc.renderAllAsync(groupName)```
But knowing that the `allCharts` argument was introduced in Oct 2017, it's possible that we just forgot to use that signature when we changed the adapter in commit [18c34d4], copying it from the `redrawAllAsync` signature, replacing 
``` …
```

[FE-8326] [FE-8330] tentative fix to render bug

---

src/core/core-async.js
src/core/core-async.unit.spec.js

Currently, `renderAllAsync` and `redrawAllAsync` throw away any requests to render/redraw if it's currently rendering/redrawing something. This PR changes the logic to keep track of requests per group:
* If the group is *not* rendering/redrawing, then it starts, even if other group(s) are rendering/redrawing;
* Otherwise,
* If a "note" has been made (see next bullet), nothing happens; request is thrown away.
* If a "note" has not been made, then it is noted that the group has requested another render/redraw. When the original render/redraw has finished, the note is deleted and the group renders/redraws again.
All of this logic assumes the `allCharts` parameter is falsey. If it is truthy, then that usurps all the logic:
* If nothing is rendering/redrawing currently, everything …

[FE-7857] block/delay repeated render/redraw requests *by group*

---

dist/mapdc.js
src/charts/heatmap.js

Heatmap axis' filter is not filtering matching timestamp values correctly, so using moment.js formatter helps to filter properly.
https://github.com/omnisci/mapd-immerse/pull/5532

[FE-8644] Heatmap Y and X axis filter for timestamp bug fix

---

package-lock.json
package.json

Update mapd-connector and mapd-crossfilter to latest versions to be up-to-date with 4.7 Thrift/Core API. Some of the examples are currently broken without this update (for getting the table descriptors)

[FE-8765] Update mapd-connector and mapd-crossfilter to latest versions

---

dist/mapdc.js
src/mixins/filter-mixin.js

Dates were being coerced to strings that didn't include milliseconds, so now any dates in filters or test values are coerced to ISO strings when being compared.
Also added documentation and split up some code for readability.

[FE-8750] Anticipate milliseconds when comparing dates in table chart

---

dist/mapdc.js
src/utils/binning-helpers.js

This fixes a bug where heatmap was binning by century for high precision timestamp datasets. It's also relevant to know that heatmap's maximum bin number is 50.
When we automatically select a bin unit for a given dataset, we try to find a unit of time ( century, decade, year, quarter, month, week, day, hour, minute, second, millisecond) that would provide less than the max number of bins while also having greater than 2 bins.  I presume we added the minimum number of bins for charts like line chart, where two data points are required to render a line. 
There are edge cases where no units fit those parameters, in which case the chart defaults to binning by century. 
For example, with a high precision timestamp dataset that spans **140 milliseconds**:
- Binning by millisecond would create …

[FE-8795] Fix auto binning for dates in heatmap with high precision timestamps 

---

dist/mapdc.js
package-lock.json
src/charts/heatmap.js

Custom dimension date formats weren't appearing correctly in heat chart - both in axis labels and popups. 
This is because the functions that created the text for rows / columns in the heat chart were passing along the information in the incorrect format. 
`customFormatter` is set to the `autoFormatter` function from mapd3, which processes raw values. However, `formatDataValue` expects an object / array of objects that contain additional information

[FE-8727][FE-8787] Fix Heat chart x-axis labels, popups display when specifying custom date format

---

dist/mapdc.js
src/charts/heatmap.js
src/utils/formatting-helpers.js

We didn't have formatting options for datasets binned on second or millisecond.
I also updated some comments / variable names in two confusing functions that assign column / row tick labels.

[FE-8788] Fix axis tick date formatting for HPT datasets in heat chart

---

dist/mapdc.js
package-lock.json
package.json
src/charts/mapd-table.js
src/charts/mapd-table.unit.spec.js
src/charts/raster-chart.js
src/mixins/raster-layer-heatmap.unit.spec.js
src/mixins/raster-layer-point-mixin.unit.spec.js
src/mixins/raster-layer-poly-mixin.unit.spec.js
src/mixins/raster-mixin.js
src/utils/utils.js

Normalize SQL building to use uppercase 'AS' for table and column aliases, to be consistent with other modules. Pulls in mapd-crossfilter and metis (mapd-data-layer) changes for the same.

[FE-8842] Normalize table and column alias SQL to use uppercase AS

---

dist/mapdc.js
src/mixins/coordinate-grid-raster-mixin.js

Relates with: https://github.com/omnisci/mapd-immerse/pull/5608

[FE-8866] Show modal for BE Scatter when WebGl is not supported

---

dist/mapdc.js
package-lock.json
src/charts/row-chart.js
src/mixins/legend-mixin.js

There was a, uh, bug?, where the color legend wasn't passing the color measure name to mapd3's `autoFormatter`. This meant that mapd3 wouldn't be able to associate the color legend values with a specific format string, and would default to the first format string found (for reasons). This commit changes it so that the color legend looks up the color measure name before formatting the legend values.
There was a bug where the X axis would only check that _some_ value formatter had been set before trying to format the X axis values, but it didn't check that the formatter had any specific formatter for the X axis. Because mapd3 will default to the first format string found if it doesn't know how to format a specific measure, this caused weirdness when the user set a color format but not a …

[FE-8836] Fix color legend & bar chart X axis formatting

---

package-lock.json
package.json

This bumps the version of crossfilter used here to pull in a fix for `NULLS LAST` in queries. See omnisci/mapd-crossfilter#88 for more info.

[FE-8908] Bump crossfilter to fix nulls last queries

---

dist/mapdc.js
src/mixins/base-mixin.js
src/mixins/coordinate-grid-mixin.js
src/mixins/multi-series-mixin.js

Use millisecond resolution for Dates in multi-series-mixin
In the `processMultiSeriesResults()` function in `multi-series-mixin.js`, add a check to see if the values be used are Date objects. If so, explicitly call `toISOString()` instead of letting it implicitly call `toString()`, so that we retain millisecond precision.
This change should fix using HPT values on histogram with a color dimension. Previously, you would only get one bin, since `toString()` cuts off milliseconds. Now, we get the proper binning.
This PR also fixes two other functions, `_title()` and `compareDomains()` to be HPT-aware. These weren't directly related to the bug in question, but were incidentally discovered in the course of fixing this bug.

[FE-8934] Fix hpt binning with colors in histogram

---

dist/mapdc.js
package-lock.json
src/mixins/coordinate-grid-mixin.js

In certain circumstances (like creating a date global filter, and just clicking inside the start/end time inputs without changing them), the Date objects in `d2` (the second domain array) are invalid. Like, they're Date objects, but were created with invalid values. I'm not sure how or why these invalid Date objects are being created, but nonetheless, calling `toISOString()` on them throws an exception.
Due to JavaScript being JavaScript, calling `toString()` does not throw an exception; it just returns the string "Invalid date". So in `compareDomains()`, we test if the Date is valid (by checking `getTime()` doesn't return NaN). If it's valid, we call `toISOString()` like normal; if it's invalid, we just call `toString()` to avoid the exception.
This bug was introduced by PR #370 …

[FE-9007] Handle invalid Date objects in `compareDomains()`

---

dist/mapdc.js
src/mixins/raster-draw-mixin.js

This is necessary for [FE-9094](https://jira.omnisci.com/browse/FE-9094).
This change just implments some refactoring for the sole purpose of exposing a `getFilterObj` method on the dcChart. We can use that method to pull out the relevant filter information for display in the pop up.
No functionality should be changing other than the newly exposed method.

[FE-9094] expose filterObj

---

dist/mapdc.js
package-lock.json
package.json
src/index.js
src/mixins/raster-layer-poly-mixin.js
src/utils/custom-sql-parser.js
src/utils/custom-sql-parser.unit.spec.js

Solution utilizes a simplified SQL parser that determines what part of the custom sql column can be moved into the "fact" query (ie, the `WITH` part of the query), and the parts that cannot. The parser doesn't understand everything, but it does understand parentheses, functions (including aggregates), and math (including precedence). That's enough to cover most use cases for now.

[FE-8901] allow both fact and geo columns in custom choropleth cols

---

dist/mapdc.js
src/charts/raster-chart.js
src/mixins/raster-layer-poly-mixin.js

Create a NON geo joined Choropleth chart, then click on a polygon to filter. Go to the Dashboard view and open the new filter panel. Click x button to clear the rowid="" filter which is the polygon selection filter. We should see all polys without any filter and bbox reappearing on the new filter panel instead of the rowid="" filter.

[FE-9568] reapply bbox filter when poly filter removed from new filter panel

---

dist/mapdc.js
package-lock.json
src/charts/number-chart.js

It seems the intention of this code is to use a cached value if the number chart is showing a count. However, this cache is only updated by the count widget, and only one count widget appears on the page when the dashboard loads. So, if this number chart _happens_ to have the same datasource as the count widget that shows up beneath the dashboard name, then it works. Otherwise, the cache is never updated, so the number chart never updates.
To make matters worse, by the time this code runs, a query has already executed to get a count. So, in the best case scenario where this chart's datasource matches the count widget's datasource, it's _still_ running a query twice. In the worst case scenario where the datasources don't match, the query runs, gets the correct value, then throws it away in …

fix issue with number charts not updating

---

src/chart-addons/dc-legend-cont.unit.spec.js
src/mixins/raster-layer-poly-mixin.unit.spec.js
src/utils/custom-sql-parser.unit.spec.js

There was an accidental .only() preventing the entire test suite from running. Removes it and fixed some of the tests that needed expected values updated

Remove .only() from parseFactsFromCustomSQL test and fix tests

---

scss/chart.scss

See https://github.com/omnisci/mapd-immerse/pull/6112

opacity of zoom and mapbox info icons

---

dist/mapdc.css
dist/mapdc.js
mapdc.css
package-lock.json
package.json
scss/chart.scss
src/charts/pie-chart.js
src/utils/formatting-helpers.js

* Adds percentage labels accounting for the sum total of all slices' values
* Adds toggling methods for both percentage labels and the original absolute value labels
* Adds an 'All Others' slice that cannot be filtered and shows the value for all remaining values on the dimension that are not represented by a specific slice.

Add percentage labels, toggle for absolute labels, and 'All Others' slice handling to pie chart

---

dist/mapdc.js
src/mixins/coordinate-grid-mixin.js
src/mixins/coordinate-grid-mixin.unit.spec.js

The getNumTicksForXAxis method in coordinate-grid-mixin was capping the number of ticks based on the chart width for normal dimensions, but not when the chart group had an extract time dimension. This change fixes that, correcting an issue with the bubble-mixin on top of it primarily.

Cap the number of ticks for extract dimension too, in coordinate-grid-mixin

---

dist/mapdc.js
package-lock.json
package.json
src/charts/pie-chart.js

Pie chart was accessing chart.data() in drawChart - in some scenarios, that can resolve to undefined just after an update, after the new percent labels / all others options were added.

Guard chart data access in pie chart drawChart

---

dist/mapdc.js
src/charts/pie-chart.js

Regenerate the popup for pie chart on every redraw in drawChart, in order to handle the cases where the data and number of slices might have changed during redraw due to the new percentage label + all others logic.

Regenerate the popup for pie chart on every redraw

---

dist/mapdc.js
src/charts/pie-chart.js

Use size measure in valueAsync call for total calculation when All Others value is enabled for pie chart, so that it calculates the proper total when the measure aggregate is not # Records (such as Sum).

Pie chart: Use size measure (first index from crossfilter reduce array) for the valueAsync call for the All Others value

---

package-lock.json
package.json

We can't call ST_GeomFromText w/o passing in a projection.
omnisci db DOES allow different projections in geostring columns, but also currently ASSUMES they're all 4326 no matter what. There's also no current way to get the projection on a geocolumn.
So we just assume that it's always 4326 and pass that into ST_GeomFromText(), even though the coordinates had already been translated into 4326 anyway.
Stops an exception from being thrown for using a differing SRID, even though they're all 4326. AFAICT, that's an old error that's only surface recently since we started reporting the exception instead of letting it die on the console.
Closes [FE-10310](https://jira.omnisci.com/browse/FE-10310)
1.
2.
3.

[FE-10310] circle exceptions

---

dist/mapdc.js
src/mixins/raster-layer-poly-mixin.js
src/mixins/raster-layer-poly-mixin.unit.spec.js

From previous work that made enableHitTesting to be dynamic is not suitable for poly right now because poly needs selection filter that requires enableHitTesting to be true. Thus, we set it to `true` always until we add a poly selection filter handler (ex: enable/disable toggle). This toggle will prevent sending constant hit testing requests which caused some issues like IQT experiences.

Make enableHitTesting always true for poly

---

dist/mapdc.js
src/charts/bubble-chart.js
src/mixins/bubble-mixin.js

[Required reading](https://github.com/omnisci/mapd-immerse/pull/6151)
See my [Immerse PR here](https://github.com/omnisci/mapd-immerse/pull/6169)
Herein lie changes that allow us to have a range slider for sized bubble charts in Immerse.
- Passes a boolean regarding whether or not the chart currently has a size measure
- Adds a default absolute minimum pixel radius for sized bubbles (bubble charts with a size measure)
- Adds a default minimum size ratio for sized bubbles
- Modifies `plotData` to have two different paths for assigning bubble size ranges, depending on whether there's a size measure or not. 
- Unsized bubbles have a fixed pixel size 
- Sized bubbles are scaled. This scale is a function of an arbitrary multiplier and the chart's width. This means that sized bubbles are …

[FE-10291] Add range slider for bubble charts

---

src/mixins/raster-layer-poly-mixin.js

Adding the special `strokeColor: "fillColor"` to make the stroke color teh same as the fill color

strokeColor: "fillColor"

---

dist/mapdc.js
src/utils/custom-sql-parser.js
src/utils/custom-sql-parser.unit.spec.js

Added support for `CASE` statements and conditional expressions to the sql parser.

[FE-10674] :sparkles: added case and conditional support to sql parser

---

dist/mapdc.js
src/mixins/ui/lasso-tool-ui.js

Fixes gap between lasso circle and filtered points by using a more precise radius for the earth. Error is reduced to about 20-30cm.

[FE-8366] Fixes gap between lasso circle and filtered points

---

dist/mapdc.js
src/mixins/base-mixin.js
src/utils/utils.js

Change uniqueId to be random, to ensure charts have unique ids in the same context but across instances

[FE-10953] [FE-10954] Change uniqueId to be random instead of incrementing

---

dist/mapdc.js
src/utils/utils.js

Same fix as for FE-10563 with the binned histograms.
EXCEPT that if you create a histogram that is _not_binned, the data value contains a scalar and not an array. So this just wraps the access of that key with an isArray check. If it is one, then we proceed as before. If not, then we return the value wrapped in an array.
Should resolve it, as long as there aren't more cases, of course.
Repro steps in the ticket, but the short version is just to create a histogram w/o bins and ensure that you don't get an error `e[n].map is not a function`

[FE-10971] - naturally, if a histogram is NOT binned, it's a scalar

---

dist/mapdc.js
src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-point-mixin.js

Pretty small PR to support bigger work for FE-11503, just ensures that the layerName is handed through when getFilterString is called, since OmniCrossFilter is now aware of it and can hand back appropriately layer scoped filters from it.

[FE-11503] call getFilterString with name

---

dist/mapdc.js
src/mixins/raster-draw-mixin.js

I'm furious about this one.
Right as I was trying to merge in my very very last PR, I see build errors. Turns out I can't include an async function. No problem! I switch it to a .then() statement.
That doesn't work - the function isn't returning a promise. "That's weird," I think. Oh well, I must've put it in over-zealously.
Nope! The await there was triggering a break in the event loop, so it'd apply filters, break out, then return and run the next line. It was a bogus hidden setTimeout() line.
And the effect of this was that the count chart didn't update when you drew a lasso.
So I restored it via a setTimeout. Bah.

[FE-11585] fixed event loop

---

dist/mapdc.js
src/charts/mapd-table.js
src/mixins/filter-mixin.js

Filters on non-grouped tables _do not work_.
This makes them work _better_.
You'd once again be able to click on a column to filter on it, including multiple filters. Clearing any one of those filters clears all the filters (as it always worked).
A table can now be loaded with a saved filter, and it will display "correctly" in that the data is filtered, but it will _not_ have the blue highlighting unless the filter is re-applied.

[FE-11658] - hacked up mapd-table

---

dist/mapdc.css
scss/chart.scss

We're defaulting axis labels to not be bold: https://omnisci.atlassian.net/browse/FE-11804

[FE-11804] Remove bold from axis

---

dist/mapdc.css
dist/mapdc.js
scss/chart.scss
src/mixins/dc-legend-mixin.js

We're updating light mode chart axis colors across the board from #aaa/#a7a7a7 etc to #868686 (which is $text-gray in Immerse)
https://omnisci.atlassian.net/browse/FE-11870

[FE-11870] Update axis/chart control colors to #868686

---

dist/mapdc.js
src/chart-addons/stacked-legend.js

PR #270 added a fix for domains that look like `["NULL", "NULL"]` - however, that fix was applying to any domain that included "NULL". This fix just tests for domains that have "NULL" more than once.
Fixes [FE-11967](https://omnisci.atlassian.net/browse/FE-11967)

[FE-11967] :bug: test for domains with cnt(NULL) > 1

---

dist/mapdc.js
src/charts/raster-chart.js
src/mixins/map-mixin.js
src/mixins/ui/coordinate-grid-raster-mixin-ui.js

The mods to maps-charting to enable shift-to-zoom.
I felt like I needed to hack up the mapbox interface a bit to do this and would've hoped there was a better way to do it. Definitely open to suggestions if there's a simpler way to enable modifier keys during interactions, but all I could find was explicitly turning the zoom/pan handlers off/on based upon the event having the shiftKey. :-(
Also needed to explicitly break it apart and add a wheel event, since otherwise it's a shift click that restores the handler. It's messy.

[FE-11589] - enable shift to zoom functionality

---

dist/mapdc.css
scss/chart.scss

Now that we allow users to change the font size of axis labels, make sure input heights adjust accordingly

[FE-11974] [FE-11924] Axis min/max input - use auto height

---

dist/mapdc.js
src/mixins/raster-layer-poly-mixin.js

When we make poly selection filter in Choropleth chart, we receive image with all polygons but colored based on filter status. Filtered polygons are colored and unfiltered polygons are grayed out. However, when we export the poly data, we only need to export the filtered polygon since there is no color information passed down to geojson file. Thus, we change the sql query to include the selected rowid in the WHERE clause.

[FE-12170] Filter poly for Data export

---

dist/mapdc.js
package-lock.json
package.json
src/mixins/raster-layer-point-mixin.unit.spec.js

Pull in metis change from https://github.com/omnisci/metis/pull/87 / 0.0.23, to use new more performant SAMPLE_RATIO function for sampling a subset of rows for render requests, instead of the MOD()-based hashing approach.
Before (both are filters in the SQL WHERE clause):
```
MOD( MOD (taxis.rowid, 2147483648) * 2654435761 , 4294967296) < 12469954
```
After:
```
SAMPLE_RATIO(0.002903387524200134)
```
The parameter to SAMPLE_RATIO is a number from 0.0-1.0 representing a probability the row will be in the results. In this case, about 0.2% of the rows will make it through. The prior MOD() sampling expression did this too, as a result of the ratio used for the rowid multiplier - so the above should be equivalent in effect.

[FE-11992] Update sampling to use new SAMPLE_RATIO function

---

dist/mapdc.js
src/mixins/raster-layer-point-mixin.js

When exporting pointmaps, we should use 4326 instead of 900913.

[FE-12211] :bug: export pointmaps in 4326

---

dist/mapdc.js
src/charts/raster-chart.js

[FE-12455] Fix typo that caused missing scatter image

---

dist/mapdc.js
src/core/errors.js
src/mixins/async-mixin.js
src/mixins/coordinate-grid-raster-mixin.js

Adds a distinct error for async render/redraws landing after a raster chart has been destroyed

[FE-12124] Handle callbacks on destroyed raster charts

---

dist/mapdc.js
src/mixins/raster-layer-poly-mixin.js

Nearly trivial fix. Just hand in the layerName to the getFilter call.

jimt/FE-12787 - passes layerName to getFilter

---

dist/mapdc.js
src/mixins/raster-layer-poly-mixin.js
src/mixins/raster-layer-poly-mixin.unit.spec.js

[FE-12805] Reflect opacity to null value - filtered poly

---

dist/mapdc.js
src/mixins/map-mixin.js

Description: 
_map.on("style.load" ...) is not called when the same style reselected, so using _map.on("styledata" ... ) to capture the same style event to reapply the rendered image after changing the basemap.

[FE-12813] Fix same basemap lost image by using styledata listener

---

dist/mapdc.js
src/utils/custom-sql-parser.js
src/utils/custom-sql-parser.unit.spec.js

The sql parser was failing if a column name began with a keyword, such as `origin_lon` beginning with `or`.

[FE-12815] :bug: fixed parsing issue: columns starting with keywords

---

dist/mapdc.css
scss/chart.scss

[FE-12895](https://omnisci.atlassian.net/browse/FE-12895)
Related: https://github.com/omnisci/mapd-immerse/pull/7401

[FE-12895] Break words in legends so they conform to user-configured width 

---

dist/mapdc.js
src/charts/raster-chart.js

After the vega spec is generated, an event is raised giving other code a chance to manipulate the spec before sending it off to the server. This is used in Immerse.

[FE-12302][FE-11372] raise an event after gen vega spec

---

dist/mapdc.js
src/charts/mapd-table.js
src/mixins/filter-mixin.js

When you click a row in table chart, the keyAccessor function runs to generate a key for that row. If there is only one column in the table, the key will be a single value (that value might be an array, in the case of binning - but it's a single value). If there are more than one columns, the key will be an array.
The code that checks if a row has a filter did no such flattening in the case where there was a single column. I switched it to use the same keyAccessor function. I also updated the function that compares the values to check variable types, too, to fix a problem with setting a filter on NULL also highlighting false, and vice versa.

[FE-13145] :bug: fixed tbl binned filter highlighting

---

dist/mapdc.js
src/charts/mapd-table.js

There's a mismatch between what Immerse uses to set the "keys" for formatting, and what mapd-charting is using as keys to get the formatting.

[FE-13276] fix table formatting again

---

dist/mapdc.js
src/mixins/lock-axis-mixin.js

When locking/unlocking the axis, call the elasticX/Y listeners after calling the domain listeners

call elastic listeners after domain

---

src/mixins/raster-layer-point-mixin.js

Adds support for the initial legacysymbol airplane icon added with this commit: https://github.com/omnisci/omniscidb-internal/commit/743081693d55e04573465e8d0262f961f5d3ae48

Adds support for the airplane symbol, legacysymbol vega mark type only initially

---

dist/mapdc.js
src/mixins/async-mixin.js
src/mixins/coordinate-grid-raster-mixin.js

Scatter plot has a couple of stupid slowdowns, reported most recently by IHS.
First of all, it will always refresh the retrieved dataURL, even if it's identical to its previous value. The fix here is just to cache the img url + the render bounds, and not bother to do anything if they're both unchanged.
Secondly, during chart creation, it ends up firing off several `redrawAsync` calls before it has even completed its initial render. `setValueFormatter`, `setElasticX`, and `setElasticY` all trigger redraws.
The best way I could see to do this was to add new functionality to `async-mixin` - `enableChartRedraw`/`disableChartRedraw`. So that way we can disable it when we start to create a scatter plot, set the values, then re-enable it when we're done. It's a stupid hack, but so's everything …

[FE-13791][IHS] - fix scatter chart related slowdowns

---

dist/mapdc.js
src/charts/mapd-table.js

I set up [https://omnisci.atlassian.net/browse/FE-13887](FE-13887) as a centralized ticket for these param/table issues. There are probably more related tickets.
This adds in a hook to mapd-table to allow us to process columns with parameters when they're pulled out for filtering purposes, as opposed to pre-processing them and storing that string on the dimension. Immerse sets the `setCustomRetrieveFilterType` function.
That, in turn, allows us to track usage only when data is fetched.
Also - mapd-table blew up when you attempted to filter on any measure columns that weren't in the table. So it's not just that `${foo}` would break, things like `avg(foo)` or `8` would also break. So this tweaks it to refuse to set a filter entirely if it's not in the table.
There may be cases where you …

[FE-13887] table param coupling

---

dist/mapdc.js
src/mixins/raster-layer-poly-mixin.js
src/utils/custom-sql-parser.js

This is a hack that I _think_ will keep us in action but it should be re-visited and done better in the nebulous future.
The problem was correctly diagnosed - the params were preprocessed before hitting the query, so usage couldn't be noted. We needed to hold onto the params until the end for the notation. However, if we did that, then it blew up at an earlier step. 
This is because custom colors are parsing out the query and building an AST and I _swear_ it's doing something with its own templating at this level, but I haven't isolated or proven that.
So this mod here just lets us override some behavior - provide a function to retrieve the color aggregate, and another function to post-process the values that come out of `parseFactsFromCustomSQL`.
Those functions are handed in via immerse …

[FE-13941][others?] params and poly stuff

---

dist/mapdc.js
src/charts/mapd-table.js

I dunno if this is really worth incorporating at this point for 5.7. It's a trivial change, but it's table chart, so it's _never_ a trivial change.
Anyway, way back in the olden days of _four years ago_, mapd-table was wired up so that when you click the sort button, it'd fire off a `redrawAllAsync` on the chart's group, which'd cause needless re-querying on other charts.
This changes to just call the single chart's `redrawAsync` in its place. I think it works, but I'll never have confidence in anything table related. 
And it looks like an ancient issue. So maybe it's not worth sticking in in the last minutes of 5.7? I dunno.

[FE-13942] - table redraw change

---

dist/mapdc.js
src/charts/mapd-table.js

Reverts omnisci/mapd-charting#543
Reverting after reproducing intermittent test failures with this change.
Test failure recording: https://user-images.githubusercontent.com/1076105/129072779-fb67a570-b82c-4641-bee3-30e3accb98ed.mp4

Revert "[FE-13942] - table redraw change"

---

dist/mapdc.js
src/charts/mapd-table.js

Reverts omnisci/mapd-charting#544
Targeted branch was determined to not be the root cause of a failing test, so reverting the rever

Revert "Revert "[FE-13942] - table redraw change""

---

dist/mapdc.js
src/mixins/raster-layer-point-mixin.js

Renames `point` to `transform` in pointmap csv exports to avoid using a [reserved word](https://docs-new.omnisci.com/sql/data-manipulation-dml/omnisci-reserved-words).

renames pointmap transform from point -> location

---

dist/mapdc.js
src/mixins/raster-layer-point-mixin.js

Only pretty-print aliases when exporting data. Custom SQL dimensions could break the generated query here, and hit-testing also seems to depend on the previous `key[#]` aliases.
(This does _not_ fix exporting data with custom SQL dimensions—wrapping the group by in quotation marks seems to generate valid SQL, but still fails validation somewhere down the line?)
Fixes FE-14191, FE-14196

[FE-14191][FE-14196] Limit pretty-printed aliases to data exports

---

dist/mapdc.js
src/charts/raster-chart.js
src/constants/paused.js

1. Enable crossfilter pausing in control-panel
2. Create dashboard with a pointmap and text chart
2. Pan/zoom on pointmap, ensuring map refreshes when crossfilters are not paused and map does not refresh when crossfilters are paused
3. Make sure table chart updates or does not update according to pause status

[FE-12207] Refactor - remove window.paused global

---

dist/mapdc.js
src/mixins/raster-draw-mixin.js
src/mixins/raster-layer-point-mixin.js
src/utils/utils-lasso.js
src/utils/utils-lasso.unit.spec.js

Also changed the airplane symbol mark to be normal "symbol" since I was in here. The airplane was added to our stock symbols for the `symbol` mark some time ago.
[FE-14661]: https://omnisci.atlassian.net/browse/FE-14661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FE-14661] Replaces distance_in_meters with st_dwithin for lasso circle filters

---

dist/charting.css
dist/charting.js
scss/chart.scss
src/charts/heavyai-table.js

This adds functionality to the table chart that allows the user to specify content alignment on a per-column basis. The buttons appear when you hover over the column, and can be accessed/manipulated via `chart.columnAlignments()`
Work will be done in Immerse to persist/populate this settings in the dashboard state.
[JIRA](https://heavyai.atlassian.net/browse/FE-15044)

[FE-15044] first draft adding align buttons to table chart

---

dist/charting.js
src/mixins/raster-layer-point-mixin.unit.spec.js
src/utils/utils-vega.js

Add necessary updates to charting to process and handle vega spec changes needed for color ramps.
Closes [FE-15240](https://heavyai.atlassian.net/browse/FE-15240)
1. Need to test through immerse - add all color ramps and verify map re-renders and vega query changed to using `threshold` when a complete set of color ramps is passed through. (Can use branch `matzy/FE-15240_color-ramp-prototype` if want to test locally in immerse)

[FE-15240] Color ramp prototype

---

src/chart-addons/stacked-legend.js
src/chart-addons/stacked-legend.unit.spec.js

My windbarb pr https://github.com/heavyai/heavyai-charting/pull/585 largely broke legend behavior, particularly for what materialized into quantize scales. This was due to changes I made down in the stacked-legend code to assist with outputs from a more formal render-vega-lite-like interface that is WIP. The vega-lite-like interace is currently embedded only in the windbarbs, but there were a handful of places downstream that were impacted by having a new "state" structure. One of those was the stacked legend behavior. This restores the original behavior for charts that have not been upgraded to the new render-vega-lite iterface that I hope to incorporate. This is done by completely restoring the original `LegendState` code, and tagging the state input with a version. The old way will be …

Restore previous legend behavior for most raster charts

---

src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-poly-mixin.js
src/utils/utils-contour.js

Since we can't use the parser to generate the sql for the contour TF, it also wasn't including the layer/global filters in the custom contour util. This takes _just_ the filters from the parser and adds those to the contour query

[FE-16027] Use parser to create filters, and apply to contour query

---

dist/charting.css
src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-poly-mixin.js

`buildContourSQL` expecting all of the chart `state`, but charting passing just the contour data. Crossed wires somewhere, this gets them on the same page.

Bad merge fix

---

src/mixins/render-vega-lite/Definitions/Encoding/Scale/Continuous/ContinuousScale.js
src/mixins/render-vega-lite/Definitions/Encoding/Scale/Discretizing/DiscretizingScale.js
src/mixins/render-vega-lite/Definitions/Encoding/Scale/Discretizing/ThresholdScale.js

The list of ranges for continuous scales (max of 25 ranges) will now be used to auto-fill in domains. Before it would only use the first two range values in the list and ignore the rest. Now, all ranges will have an associated domain value, therefore all range values will be represented in the scale. This is achieved by filling in a new vega formula expression for each "stop"/"subdivision" in the range list.
Opportunistically fixed some other minor issues as well.

Auto fills continuous scale domains to align with number of ranges.

---

package-lock.json
package.json
src/charts/raster-chart.js
src/mixins/raster-draw-mixin.js
src/mixins/raster-layer-mesh2d-mixin.js
src/mixins/raster-layer-point-mixin.js
src/mixins/raster-layer-windbarb-mixin.js
src/mixins/raster-layer.js
src/mixins/ui/lasso-shapes/LatLonCircle.js
src/mixins/ui/lasso-shapes/LatLonPoly.js
src/mixins/ui/lasso-shapes/LatLonViewIntersectUtils.js
src/mixins/ui/lasso-tool-ui.js
src/utils/utils-latlon.js
src/utils/utils-vega.js

Prior, the commit the mapd-draw dependency was pointing to was pre-rebranding efforts, so to move to a top-of-branch commit meant we needed to update all the mapd-draw-related import statements to reflect the rebrand-related naming. So paths such as `@heavyai/draw/dist/mapd-draw` needed to be updated to `@heavyai/draw/dist/draw`

Update mapd-draw dependency to latest commit

---

example/exampleLineCrossSection.js
src/mixins/ui/lasso-event-constants.js
src/mixins/ui/lasso-tool-set-types.js
src/mixins/ui/lasso-tool-ui.js

Fixes the bug noted here: https://github.com/heavyai/heavyai-charting/pull/609#issuecomment-1334030150
Also includes an expansion of the event system to include some useful signals to help monitor situations where a cross-section line is deleted when a new cross section line is drawn. This was done as it may be useful to avoid re-drawing the cross section chart in that case and instead wait for the new line draw to complete. The client can check for that case with some new event extensions, namely the:
`LASSO_TOOL_TYPE_ACTIVATED`/`LASSO_TOOL_TYPE_DEACTIVATED` events
or the
`LASSO_TOOL_DRAW_STARTED`/`LASSO_TOOL_DRAW_ENDED` events

Enforces cross-section line draw rule by only allowing one drawn cross section at a time

---

src/index.js
src/mixins/raster-draw-mixin.js
src/mixins/raster-layer-mesh2d-mixin.js

Exports constants, guards against some conditions Immerse hits. Asserts for range removed as it is undefined when filterAll is called, which I doubt is new behavior. Added a noop for dispose as cross section seems to only have a dimension proxy.

[FE-15866][FE-16067] integrate line select tool + prevent error on destroy cross section

---

src/mixins/raster-layer-poly-mixin.js

The color scale generation needs a bit of investigation/iteration in immerse to match with the TF output, but in the meantime and as a fallback we'll clamp values off the end of the contour polygon fill scale to the ends of the fill scale
Before:
After:
With a filter:
Before:
After:

[FE-16149] Add clamp option for contour polygons color scale

---

src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-poly-mixin.js
src/utils/utils-contour.js

SQL generation code was written with the assumption that the field passed in was a field name, but can be an expression. This changes to use a const for output field alias.

[FE-16190] Fix SQL to accept custom measures

---

src/mixins/raster-layer-poly-mixin.js

Previously polygon layer had a default `onClick` function which filters by the poly selected.  This is not wanted for contour (especially since it interferes with the cross-section line tool), so adding a new settable property to the layer which can be used to bypass this function.
This fixes an issue with the line tool in contour where the `onClick` handler for this layer would fire when a user clicks to start or end a line, and filter out all the results from the data set.

[FE-16237] Set new prop to avoid filtering on clicked poly for contour

---

src/chart-addons/stacked-legend.js
src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-poly-mixin.js
src/utils/utils-contour.js
src/utils/utils-vega.js

In order to have multiple contour charts in one layer, we need to name the scales on a per layer basis. This includes the layer name for each scale so that we can have multiple color, width scales in the same vega spec. 
This also refactors a small bit of legend code to make sure the domain is an array, and make the check a little simpler

[FE-16290] Contour multilayer support

---

src/mixins/raster-layer-line-mixin.js

Creating the `xDim` and `yDim` getter/setters by default fixed the contour bbox filter issue, but broke linemap (assuming there is some check later down the line for these that sends it down a different codepath).  Thus, simple solution is to wrap the creation of these properties in a method that can be called from contour, to allow them to be accessible to contour but not be automatically set-up for linemap.

[FE-16243] Create new method to setup x and y dims just for contour

---

dist/charting.css
scss/chart.scss
src/charts/raster-chart.js
src/mixins/base-mixin.js
src/mixins/coordinate-grid-raster-mixin.js
src/mixins/label-mixin.js
src/mixins/scatter-mixin.js

Adds support for adding an additional y-axis to the coordinate-grid-raster-mixin, currently used by backend scatter, cross section, and cross section terrain.  Modifies the mixin and its HTML generation process to support right y-axis rendering when `useTwoYAxes` is set.  Additionally, adds a `chart.y2` prop, which is then set in the presence of a multi-layered cross section chart based on the terrain layer.  While this currently will always ensure the terrain layer gets the y2 axis, this should allow any layer to take the y2-axis with slight future modifications.  
Closes [FE-16795](https://heavyai.atlassian.net/browse/FE-16795) [FE-16796](https://heavyai.atlassian.net/browse/FE-16796)
1. Create a cross section chart, make sure only left y-axis appears with correct scale
2. Add a terrain …

[FE-16795] [FE-16796] Add second y-axis, ensure y-axes alignment

---

src/charts/raster-chart.js

Adds new API to allow log scales to be set for charts' y-axes

[FE-16826] Add config options for d3 scale type

---

src/chart-addons/stacked-legend.js
src/charts/raster-chart.js
src/mixins/raster-layer-mesh2d-mixin.js

😌  The position was all driven from the `useMap` argument passed to raster chart. This enabled individual layers to determine their own legend position but falls back to the `useMap` logic
This also calls the same format function that legend v1 calls so we don't get crazy precision in the legend values (eg. 45.123853434534)
Before
After:
Legend Position:
Format legend values:

[FE-16842] Show legend in bottom left for mesh2d layers (cross section)

---

src/mixins/map-mixin.js

Fixes the lat/lon validation function, so that a single point (with identical lat and lon bounds) can be zoomed to.  In addition, pushes the `maxZoom` level and padding sent from immerse to the mapbox api.
For more details, see: https://github.com/heavyai/immerse/pull/8950

[FE-16757] [FE-16756] Fix lat/lon validation, send maxZoom and padding to mapbox

---

src/mixins/map-mixin.js

Positioning layer wasn't passed when re-adding render layer on style change. This should place the render layer under the label layer.

[FE-17159] Changing the style of the map is affecting layer ordering

---

src/mixins/map-mixin.js

Adds forceResize property, which will bypass width/height delta checks to force a resize (needed for layer drawer, as chart will have same w/h but needs a resize since mapbox is detecting the size of the actual canvas element and will thus leave a gray area once the drawer is gone).
Now also includes hack to get mapbox to cooperate when we have an overlay drawer rendered overtop of it.

[FE-17163] Add forceResize property

---

src/mixins/map-mixin.js

If you zoom in the chart editor and cancel, you will occasionally run into a mapbox error saying "a source with this id already exists".  Add an additional check by source id to ensure the source doesn't already exist and avoid console error if it does.

[FE-17174] Check to make sure a source with id doesn't already exist to avoid mapbox error

---

src/mixins/map-mixin.js
src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-poly-mixin.js

Big Changes:
* Updates transforms for line and poly mixins, so that if the datasource is a join it will group by the geometry table's `rowid`
* Line map wasn't using the join datasource properly, if it detects that the layer uses a join datasource it uses `table`which is the join datasource parameter, which will be processed to the full syntax down the line. 
* Use full `table.column` expression for rowid because for join data sources both tables have a rowid. 
* Some syntax improvements

[FE-17191] Join to geo support

---

src/mixins/raster-layer-line-mixin.js
src/mixins/raster-layer-point-mixin.js
src/mixins/raster-layer-point-mixin.unit.spec.js
src/mixins/raster-layer-windbarb-mixin.js

This moved the `SAMPLE_RATIO` part of the query codegen in metis to the end of the `WHERE` clause.  See ticket for details.
We may need to fix this for contour as well, but need to consult with Dr. Flaxman.  This addresses the immediate SCE issue.

[FE-17337] Move sample to end of query for metis codegen

---

src/chart-addons/stacked-legend.js
src/mixins/raster-layer-poly-mixin.js

Adds `auto-contour` color domain handling to calculate domain from min/max; cannot use existing "auto" domain logic as-is as that presumes there is a `color` column.

[FE-16380] Contour chart: Filtering values does not affect overall color range

---

src/utils/utils-contour.js

Test Dashboard
`mapd/dashboard/9368?filterSet=-NjJkvetcVtlF9fRxlYw&tab=-NjJkverljUTOKmJnkPn`
This raster has a large enough stride that bin dim meters min/max are quite large. Try setting this value throughout the whole range. 
Very large values caused the original error, and were being forced into incorrect types for the TF by calcite. This forces them to be floats, and prevents our optimization constant from getting to 0.

[FE-17341] Fix divide by 0 error, handle large bin_dim_meters param values

---

example/webpack.config.js

Broken here: https://github.com/heavyai/heavyai-charting/pull/585/files#diff-7dd57a4f662248b39cb60c9020a05a60bad59359a915a5ac35b9699cf7bf1095L6
But all of the examples still import `app.bundle.js` which is named after this property, not sure why the change was included as part of that. Fixes use of global variables like `DbCon` in the examples.

[YOLO] Fixes examples bundle name heavyai-charting -> app

---

src/charts/heatmap.js
src/charts/row-chart.js
src/mixins/cap-mixin.js
src/mixins/coordinate-grid-mixin.js
src/mixins/coordinate-grid-raster-mixin.js
src/mixins/d3.box.js
src/mixins/raster-layer.js

Catches missing hit test column error string returned from BE and replaces with human-readable error message.
For proof, here is me forcefully pushing an invalid column into the hit testing, showing the correct error coming back from the BE (and showing no crash):
https://github.com/heavyai/heavyai-charting/assets/15268289/9b229c9d-a6e4-41e0-8e39-a4208be70507
Here is after the FE fix to turn that into a human-readable error message:
https://github.com/heavyai/heavyai-charting/assets/15268289/25e3221c-e4b8-4699-86f6-c89ab597028b

[FE-17686] Human-readable missing hit test cols error string

---

src/chart-addons/stacked-legend.js
src/charts/heavyai-table.js
src/charts/raster-chart.js

This adds dynamic filtering to the legend for charts using a categorical legend.  Previously the original domain and range were being passed around in this part of the code, and no attempt at retrieving an updated domain was done for legends with categorical data.  Thus the legend displayed the initial domain, regardless if bbox/crossfilters/chart filters/etc were applied.  Now, when we detect categorical data, we make a call to crossfilter for the categorical field, get the updated topN values, pull the original range value (color) applied to each of the new topN values, and provide the legend with an updated domain and range.  This fixed the issue for pointmap, but did not for choropleth, due to a crossfilter bug (feature?).  That is fixed in this accompanying immerse PR: …

[FE-17705] Dynamically update categorical legend domain

---

src/mixins/raster-layer-point-mixin.js

Was something I changed for sql notebook pointmap v1, which became no longer needed once we switched to deckgl charts for sql notebook, and introduced a bug with Prioritized Colors in Pointmap.  Revert as this buggy revised codepath is no longer needed.

Revert "[FE-17393] Add queryoverride propery (#664)"

---

dist/charting.css
scss/chart.scss
src/charts/heavyai-table.js

Fixes issue where if table chart was resized to a small size, the column alignment buttons would float over the column name and sort button.  Now the alignment buttons will move as close as they can to the column title before getting cut off.  Moved these buttons to their own wrapper, with a flexbox layout and less padding so the buttons can get closer to the column title before being cut off.
Closes [FE-17481](https://heavyai.atlassian.net/browse/FE-17481)
1. Follow repro steps in corresponding jira ticket
2. Ensure the alignment buttons no longer overlay over the sort button and you can still sort a column when the table is resized to be very small.
https://github.com/heavyai/heavyai-charting/assets/15268289/c68b0b1a-dd83-4507-a45d-a056fb8cebee
[FE-17481]: …

[FE-17481] Preven table sorting option from being hidden

---

package-lock.json
package.json
src/chart-addons/stacked-legend.js
src/charts/raster-chart.js

- Adds sort functionality to listener which is called by legendables
- Accounts for both stacked and non-stacked nominal legends
- Sorts domain, then updates layer state, before optionally appending "Other" category and then updating legend state
https://github.com/user-attachments/assets/cd1e2c1c-47ef-4462-a88c-34ef7544776e

[SPIKE] Sortable legend

---

src/mixins/color-mixin.js

- Add hash function into charting
- When assigning colors to string values, use hash function instead of d3 coloring

Add hash coloring functions for d3 charts; call when value is string

---

src/mixins/raster-layer-line-mixin.js

Corrects function name; `lastFilteredSize` does not exist

[FE-16381] _layer.lastFilteredSize is not a function 

---

src/charts/pie-chart.js

Addresses issues with d3 domain setting - previously, when we have a palette mapping, by sending in `domain` and `range` to `maybeUpdateAllOthers`, we were sending in the mapping's domain/range - which, if created by a different chart, could be much larger than what the pie chart is displaying, leading to discrepancies between `CustomColorsList` and what was actually shown on the chart.  Since `maybeUpdateDomainRange` updates `_chart.customDomain/Range()`, pass that into the next function instead so we are using the updated domain for pie.
Bubble chart did not suffer from this bug as it doesn't have all others, so was never making that second function call that messed up the domain/range.

[FE-18033] Don't pass in stale domain to maybeUpdateAllOthers

---

src/charts/bubble-chart.js
src/charts/pie-chart.js
src/mixins/color-mixin.js

Issue was a fail to safeguard against `customRange` being undefined, which threw an error, but then also was triggering a `setCustomDefaultOtherColorValue` call in immerse, which wiped out the `paletteMappingId` on `chart.color` for D3 charts, causing the mapping not to be selected when returning to the chart.

[FE-18003] Bug fix - modifying mapping and cancelling removed mapping

---

src/charts/bubble-chart.js

Should be `let` instead of `const` as they may get overwritten by mapping domain

[HOTFIX] Fix bubble chart error

---

src/chart-addons/stacked-legend.js

Ensures getLegendStateFromChart returns sorted domain + makes value of color.sorted match current sort direction

[FE-18087] Raster chart re-render reverts legend sorting

---

dist/charting.css
package-lock.json
package.json
src/chart-addons/stacked-legend.js
src/charts/raster-chart.js
src/mixins/color-mixin.js
src/utils/color-helpers.js

Depends on legendables PR: https://github.com/heavyai/legendables/pull/12
When `fullColorHashing` is enabled, revise the legend so that it has infinite scrolling, so that it will continuously load up more values from crossfilter until it has reached the end of the data.  This also changes the initial rendering of colors on the legend - rather than pulling colors from the initial domain (as defined by immerse), it will instead first look for any customized colors, and hash the rest of them to match with the new `fullColorHashing` querying.
By default loads results in batches of 50.  Legend filtering should still work, and should only load as many columns as are available per the current bounding box.  Also moves hashing function to separate helper function.

[FE-18169] In fullColorHashing mode, add infinite scroll to legend

---

.npmignore
package.json
scripts/preinstall-if-root.js

Create script to only run `npm-force-resolutions` if building as a stand-alone library.  This will prevent it from running that package when building charting in the immerse dep install process, which causes the build to fail.

[HOTFIX] Preinstall script to conditionally run npm-force-resolutions
